cc_library(
    name = "paren",
    srcs = ["paren.cc"],
    hdrs = ["paren.h"],
)

cc_test(
    name = "paren_test",
    srcs = ["paren_test.cc"],
    deps = [
        ":paren",
        "@catch2//:catch2_main",
    ],
)
