cc_library(
    name = "buses",
    srcs = ["buses.cc"],
    hdrs = ["buses.h"],
)

cc_test(
    name = "buses_test",
    srcs = ["buses_test.cc"],
    deps = [
        ":buses",
        "@catch2//:catch2_main",
    ],
)
