cc_library(
    name = "islands",
    srcs = ["islands.cc"],
    hdrs = ["islands.h"],
)

cc_test(
    name = "islands_test",
    srcs = ["islands_test.cc"],
    deps = [
        ":islands",
        "@catch2//:catch2_main",
    ],
)
