cc_library(
    name = "locked",
    srcs = ["locked.cc"],
    hdrs = ["locked.h"],
)

cc_test(
    name = "locked_test",
    srcs = ["locked_test.cc"],
    deps = [
        ":locked",
        "@catch2//:catch2_main",
    ],
)
