cc_library(
    name = "obstacles",
    srcs = ["obstacles.cc"],
    hdrs = ["obstacles.h"],
)

cc_test(
    name = "obstacles_test",
    srcs = ["obstacles_test.cc"],
    deps = [
        ":obstacles",
        "@catch2//:catch2_main",
    ],
)
