cc_library(
    name = "bst_reorders",
    srcs = ["bst_reorders.cc"],
    hdrs = ["bst_reorders.h"],
)

cc_test(
    name = "bst_reorders_test",
    srcs = ["bst_reorders_test.cc"],
    deps = [
        ":bst_reorders",
        "@catch2//:catch2_main",
    ],
)
